### ISSUE TITLE
Which pipe plugin are you using ?

### ISSUE THREAD

**Issue by danielo515** [citycide/param.macro#10]
Hello,

I'm trying your code and I see that it does not works with any pipe operator. I'm using [babel-plugin-pipe-operator-curry](https://github.com/haskellcamargo/babel-plugin-pipe-operator-curry)

and with the following code:

```js
const add = _ + _
const tenPlusString =
  it
  | parseInt(_, 10)
  | add(10, _)
  | String

```

I get the following compiled code which is wrong:

```js
const add = (_arg, _arg2) => {
  return _arg + _arg2;
};

const tenPlusString = (_it, _arg3, _arg4) => {
  return String(add(10, _arg4)(parseInt(_arg3, 10)(_it)));
};
```

Could you please specify with which plugin are you compatible ?
Regards

**Comment by citycide** [comment]
There's an [official plugin](https://github.com/babel/babel/tree/814fce946d0b5646682b00c00b6c6b4ecc9ee26a/packages/babel-plugin-proposal-pipeline-operator) in babel v7 here, based on the actual proposal to the spec.

However be aware there's some turbulence with that plugin & the proposal while the TC39 crew works out the various details.
