### ISSUE TITLE
On bootstrapping (using param.macro in its own source)

### ISSUE THREAD

**Issue by citycide** [citycide/param.macro#18]
> **NOTE:** this issue has no bearing on _users_ of this package, and is strictly an internal development concern.

#### lay of the land

`param.macro` has used itself in its source since its initial release. npm packages can't depend on themselves so it does this by leveraging `npm link && npm link param.macro` to bootstrap itself. Recently there was a [build step upgrade](https://github.com/citycide/param.macro/pull/14) put forward by @Andarist to make this more pleasant with a CLI tool called [`npm-self-link`](https://github.com/Andarist/npm-self-link)

#### the problem

While it's cool to be able to use `param.macro` on itself and dogfood the product, it doesn't come without issues.

* dependence on locally built sources

  Because we depend on the locally built sources, development can become a train wreck when you make changes that break stuff. Now, your local build won't build your new sources correctly or will fail entirely. One solution is to scrap all changes to the `dist` built files and rebuild, but even this can fail in certain edge cases.

* built files have to be included in source control

  The `dist` directory contains the build output and has to be included in the repo. If it isn't, there's nothing to bootstrap from in a fresh clone. This means we have to ensure that the remote `dist` files are up to date & working whenever changes are made.

#### the way way forward

As I see it, there are ~3~ 4 options to work with or around this.

1. keep the status quo

   Don't change anything and deal with the current state, which has led even me to frustration while trying to make fixes or add features.

2. maintain a known functional & compatible source for the distributed files

   This is similar to the current method but rather than using a local build to bootstrap, we'd need to use a remote build that's able to compile the local sources. This still leads to the maintenance burden of keeping this up to date, and `param.macro`'s source likely just isn't large enough to justify this burden.

3. ditch bootstrapping entirely

   I'm pretty sure this is the option I'm going with. It's been a fun experiment but I don't think it's worth the cost &mdash; we'll spend as much or more time making sure bootstrapping works as we will working on the actual library. And the first time any potential contributor tries to work on the library and runs into a broken local bootstrap it's probably too late (it's already hit me a couple times).

4. just add a dev dependency <sup>derp</sup>

   npm doesn't allow an explicit `npm i [-D] param.macro` while in `param.macro`, but it doesn't prevent installing that same dependency if you just manually add it and run an install afterward. Yarn allows both.

#### discuss

Feel free to discuss. ~Soon I'll probably move on going with option 3 and ditch bootstrapping. Unfortunately this makes the recent build step improvements moot, so I do have to apologize to @Andarist who contributed that and kickstarted `npm-self-link`. I'm sure I'll find other uses for the package at some point, though.~

_Edit:_ Given the revelation behind option 4, it'd be pretty simple to just go with that.

_Edit 2:_ Option 4 is implemented.

**Comment by Andarist** [comment]
Would be interesting to see how others deal with it - I think babel, lerna, jest, rollup & others are bootstrapping their projects.

Actually I had no idea that this was also used here in source files, I had similar problem in other project which lead to my PR here, but I personally need this only for testing purposes - not for the source compilation, so it's generally not a problem for my projects. But I see how this is a problem for this one.

**Comment by citycide** [comment]
Babel & lerna can do it because they're in a monorepo structure where a top level package.json contains dependencies that the lower level packages don't but can still access above. I'm not sure that jest tests itself, but the most interesting of those projects was `rollup`. It literally has a [dev dependency on itself](https://github.com/rollup/rollup/blob/38f3ca676ba67d740ef5cd2967f8412f80feeafe/package.json#L98) which I thought was disallowed.

_Apparently_, and I can't find this documented anywhere, while npm won't let you explicitly use `npm install --save-dev current-package` to add that dependency it won't actually do anything to prevent installing it if you just add the dep manually to your `package.json` and run a bare `npm install`.

Yarn on the other hand seems perfectly ok with simply adding a project to itself as a dev dependency, or even as a regular dependency with `yarn add current-package`.

That means it'd be a lot simpler to just have a dev dependency on the last version of `param.macro`. Guess we've been overcomplicating things 🤦‍♂️.

**Comment by citycide** [comment]
Fixed in https://github.com/citycide/param.macro/commit/ddc63e78940fd77783d8deedc1d1d3df9221d9f3

The dev experience is already so much better!
