### ISSUE TITLE
Typescript Intellisense

### ISSUE THREAD

**Issue by linonetwo** [citycide/param.macro#19]
Is it possible to add typing so `it` reflects it is a function parameter?

**Comment by citycide** [comment]
You'll have to write a declaration file, something like this:

```ts
declare module 'param.macro' {
  export const _: any
  export const it: (...args: any[]) => any
  export const lift: (expr: any) => () => any
}
```

I don't imagine this would be useful for type info but maybe for usability purposes it's ok.

**Comment by citycide** [comment]
Feel free to discuss but I'm going to close since this is currently outside the scope of the project.

**Comment by ghalex** [comment]
Hi @citycide I still don't understand how should we use this with Typescript. I tried this:

```ts
const item = {id: 2}
const arr = [{id: 1}, {id: 2}]
const ndx = arr.findIndex(it.id === item.id);
```

gives me an error of:
`Argument of type 'boolean' is not assignable to parameter of type ...`

Do I miss something here ?

**Comment by citycide** [comment]
@ghalex it's highly unlikely there's any typing you'll be able to do that will give you the full range of features, unfortunately. We'll need TypeScript compiler extensions most likely and there's nothing official for that right now.

The problem in your case is that `findIndex` is typed as expecting something like `(el: T, i: number, arr: T[]) => boolean` and you're simply passing an expression that evaluates to `boolean` (`===` equality). There's currently no way of telling TypeScript that `param.macro` transforms that expression into the kind of function `findIndex` expects.

I'm happy to accept changes here that make TypeScript support possible but I don't imagine it'll be easy.

**Comment by LifeIsStrange** [comment]
@haltcase That's very unfortunate to hear, I hope the situation will improve eventually. The world is moving to typescript (BTW kotlin js now generate d.ts files !)
It seems that it is possible to create compiler plugins:
https://www.typescriptlang.org/tsconfig#plugins

**Comment by haltcase** [comment]
@LifeIsStrange I agree, I have also personally switched to TypeScript for many projects and miss `param.macro` every time 😄

I'm fairly certain a compiler plugin would be capable of this, but as far as I know this currently requires a separate wrapper around the compiler to enable their use in most cases, see [ttypescript](https://github.com/cevek/ttypescript). I've considered doing this but have not explored the compiler API enough.

**Comment by linonetwo** [comment]
Wait...Are you taliking about using param.macro in the TS project?

AFAIK macro works well in the TS, as long as you are using babel + ts , see [https://github.com/linonetwo/template-based-generator-template/blob/master/src/data/index.ts](https://github.com/linonetwo/template-based-generator-template/blob/master/src/data/index.ts) for an example!
