### ISSUE TITLE
Placeholders: stop upward traversal at `ObjectProperty`

### ISSUE THREAD

**Issue by citycide** [citycide/param.macro#2]
I'd like input on this one in terms of what's expected. I'm proposing that when placeholders are used in the value of an `ObjectProperty`, upward traversal will stop at that object property, causing the expression to be transformed essentially in place rather than wrapping the `CallExpression` further up.

**input:**

```js
doSomething({
  key: _ + _
})
```

**current:**

```js
;(_arg, _arg2) => {
  return doSomething({
    key: _arg + _arg2
  })
}
```

**proposed:**

```js
doSomething({
  key: (_arg, _arg2) => {
    return _arg + _arg2
  }
})
```

The current transformation seems like it allows for too much complexity in my opinion, like in this example:

```js
getNameByIdAsync(id)
  .then(doSomething({
    name: _,
    /*...*/
  }))
```

**Comment by wcjohnson** [comment]
OK, some thoughts:

- My first flash of intuition, without thinking about it too deeply, is that the current compilation is what I would have expected it to be.

- Digging a little more deeply, a JS object is often used as a substitute for named parameters, so these two things should probably do roughly the same thing:
```js
f(_)
```
```js
f({firstNamedArg: _})
```
The current compilation technique appears to satisfy this rule of thumb.

- OTOH, it's certainly easy to come up with examples where the other behavior is desired as well, like:
```js
dataSet.mapReduce({
  map: _ + 1,
  reduce: _ * _
})
```

So not an easy call one way or another, it seems whichever choice you make would hamper some relevant use cases.

This is the sort of stuff that made me want to get explicit about where the function boundaries are when I did `placeholderArgs` for LSC.

**Comment by citycide** [comment]
Good points, thanks!

> So not an easy call one way or another, it seems whichever choice you make would hamper some relevant use cases.

Agreed, I'm pretty split. I'm going to think on this one for a while but will probably end up sticking with the current output. Both can allow for arguably "_too complex_" constructs, so maybe it's best to stick with the current strategy.

**Comment by citycide** [comment]
Yep, let's keep the current logic of wrapping the first `CallExpression` to which the placeholder's an argument. This keeps it consistent in all cases and object methods like this could still be defined outside the object, ie. in these contrived examples:

```js
const map = _ + 1
const reduce = _ * _

dataSet.mapReduce({ map, reduce })
```

Thanks again for the input @wcjohnson

**Comment by citycide** [comment]
Stopping in to note this is actually possible now by explicitly using the [`lift`](https://github.com/citycide/param.macro#lift-modifier) modifier added in v2.1.0:

```js
import { _, lift } from 'param.macro'

dataSet.mapReduce({
  map: lift(_ + 1),
  reduce: lift(_ * _)
})
```

... which will become:

```js
dataSet.mapReduce({
  map: _arg => {
    return _arg + 1
  },
  reduce: (_arg2, _arg3) => {
    return _arg2 * _arg3
  }
})
```

`lift` is simply a dummy function that's removed entirely but essentially acts as signal to the other macros to stop upward traversal.
