### ISSUE TITLE
`it` with assignment

### ISSUE THREAD

**Issue by thisredone** [citycide/param.macro#20]
Is something like this not possible?
```javascript
foo.forEach(it.bar = true)
```
The output of that is:
```javascript
foo.forEach(
  (_it2.bar = _it2 => {
    return true
  })
)
```
Which produces an error.

I was expecting it to compile into this:
```javascript
foo.forEach(_it2 => {
  return _it2.bar = true
})
```

**Comment by citycide** [comment]
Hey @thisredone, this is probably an unwanted side effect of the top-level assignment handling. I don't there's any cases where the current output is desired so this should be fixed.
