### ISSUE TITLE
Upgrade to babel-plugin-macros

### ISSUE THREAD

**Issue by kentcdodds** [citycide/param.macro#6]
The project was renamed from `babel-macros` to `babel-plugin-macros` to better support babel v7. No other breaking changes.

**Comment by citycide** [comment]
@kentcdodds already taken care of ([`e8018a7`](https://github.com/citycide/param.macro/commit/e8018a7f29818522e6dcc1e343f4782d126ccb3b?w=1) & [`72f6bae`](https://github.com/citycide/param.macro/commit/72f6bae76d770ebc41156b050c9f0b87e7aadc04?w=1)) 😄 thanks!

**Comment by kentcdodds** [comment]
Haha! I'm not sure how I missed that. Thanks so much! 🎉
